baseURL = "https://www.green-roof-solar.com/"
languageCode = "en-us"
title = "Green Roof Solar"
theme = "ananke"

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Locations"
    url  = "/locations/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "about/images/icon.png"
  description = "Solar panels prices have fallen 80% in the last few years and utility bills have continued to rise. Install American Made solar panels on your home to save money on your monthly power bills and to help save the environment. Solar energy creation continues to climb. Join the solar revolution now!"
  facebook = "https://www.facebook.com/solargreenroof"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  yelp = "https://www.yelp.com/biz/green-roof-solar-sebastopol"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/green-roof-solar-sonoma-ca.jpg"
  recent_posts_number = 4